### PR TITLE
Added Klaytn Mainnet in pokt network

### PR DESCRIPTION
**Pull request by praveen-klaytn**
# Description

* #351 Added Klaytn Mainnet details in pokt network

Resolves https://github.com/WalletConnect/blockchain-api/issues/351

## How Has This Been Tested?

* Ran individual test for pokt network, but got an error for Klaytn availability in wallet connect even though its present in the list https://docs.walletconnect.com/advanced/multichain/chain-list

Screenshot 2023-11-03 at 9 34 25 PM

Below image shows overall test run.
Screenshot 2023-11-03 at 9 46 22 PM

## Due Diligence

* [ ] Breaking change
* [X] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by praveen-klaytn** [comment]
Hi @geekbrother , could you please help reviewing this item and let me know if any changes are required. Thanks in Advance !

**Comment by melcorprotrade** [comment]
4AEE18F83AFDEB23

**Comment by praveen-klaytn** [comment]
Hi @xav @geekbrother , could you please help in checking the PR and let me know if any further changes to be made.

**Comment by geekbrother** [comment]
Closing this one in a favor of #513

**Comment by geekbrother** [comment]
#513 is merged, Klaytn was added. @praveen-klaytn

**Pull request closed without merging**
